
// Instead of fetching notes.json, we define the notes directly
const notes = [

      "Hey babe, tumhari muskaan uss baarish ki boond si hai, jo thakawat ke jungle mein ek chhoti si jheel banakar dil ko sukoon deti hai.",
        "Hey babe, tum pyaar ki uss kitaab ki tarah ho jise baar-baar padhne ka mann karta hai, phir bhi har baar kuch naya milta hai.",
          "Hey babe, tum par bharosa karna mere liye hawa mein saans lene jaisa hai—bina soche, bina ruke, bas natural.",
            "Hey babe, tumhari woh chhoti chhoti baatein mujhe roz ek nayi duniya dikhaati hain, jahan sab kuch pyaara aur narm lagta hai.",
              "Hey babe, tum ek jaadu ho jo har subah ko nayi roshni deta hai, aur har raat ko sapno se bhar deta hai.",
                "Hey babe, tum uss kahaani ki tarah ho jise main sapno mein jeeta hoon, lekin tum toh meri haqeeqat ho.",
                  "Hey babe, tumhare saath masti karna kisi fairy tale mein ghus jaane jaisa lagta hai—sab kuch magical ho jaata hai.",
                    "Hey babe, tumhari aankhon mein imagination ki ek nadi beh rahi hoti hai, jisme main khud ko baar-baar doobte hue mehsoos karta hoon.",
                      "Hey babe, tum uss hari bhari zameen ki tarah ho jahan thakan gir jaati hai aur khushi ugti hai.",
                        "Hey babe, tum ek nadi ki tarah ho—kabhi shant, kabhi behti, lekin har dafa dil se guzarti ho.",
                          "Hey babe, jab tum asmaan ki taraf dekhti ho na, lagta hai tumhara dil bhi vahi hai—gehra, khula, aur roshni se bhara hua.",
                            "Hey babe, tumhare lafzon mein Urdu ki mithaas hai, jaise kisi sher mein mehfil bas gayi ho.",
                              "Hey babe, tum mere din ki roshni ho, aur raat ke andhere mein woh ek chhoti si lau jo kabhi bujhti nahi.",
                                "Hey babe, tum sardi ki dhoop jaisi ho—narm, halka, aur poori rooh ko garam karne wali.",
                                  "Hey babe, tum ahiqmizazi ka wo jazba ho jo poetry ke beech se chhalk kar zindagi mein aa gaya hai.",
                                    "Hey babe, tum itni hot ho ki agar tum ek mausam hoti, toh har din AC chalana padta.",
                                      "Hey babe, tum mein woh confidence hai jo andheron mein bhi apni roshni le aata hai.",
                                        "Hey babe, main tum par itna vishwas karta hoon ki agar tum kaho chaand niche le aao, toh main rassi leke chadh jaaun.",
                                          "Hey babe, tumhari soch mein ek aisi wisdom chhupi hai, jisse poora sansaar thoda aur behtar ho sakta hai.",
                                            "Hey babe, tum creative hi nahi ho, tum khud ek art piece ho—ek masterpiece.",
                                              "Hey babe, tum painting ki woh stroke ho jo dull canvas ko bhi zinda bana deta hai.",
                                                "Hey babe, tumhara charm kisi jaadu ki tarah chhup kar kaam karta hai—kabhi baaton mein, kabhi khamosiyon mein.",
                                                  "Hey babe, tum apne sabse vulnerable pal mein bhi itni pyaari lagti ho ki meri aankhon mein bas tumhari hi tasveer reh jaati hai.",
                                                    "Hey babe, tum woh romance ho jo diary mein nahi, dil ke kisi kone mein likha jaata hai.",
                                                      "Hey babe, tumhare saath bitayi woh pehli date mere liye kisi holy memory se kam nahi thi.",
                                                        "Hey babe, tumhari hansi meri subah ki chai jaisi hai—bin uske kuch adhoora lagta hai.",
                                                          "Hey babe, tum narmi se bhari hui ho, jaise baarish ke baad mitti ki khushboo.",
                                                            "Hey babe, tum jaise har season ka apna rang ho—kabhi chanchal jaise basant, kabhi gehri jaise sardiyan.",
                                                              "Hey babe, tum khud mein ek kahaani ho—aur main har din usse phir se padhta hoon.",
                                                                "Hey babe, tumhari aankhon mein wo baat hai jo kisi kitaab mein nahi, sirf mehsoos ki jaa sakti hai.",

     "Hey babe, tum jab chhoti chhoti baaton par khush hoti ho na, lagta hai duniya ki sabse badi jeet mil gayi.",
       "Hey babe, tumhara naam mere liye sirf ek shabd nahi, ek ehsaas hai jo har saans ke saath jud gaya hai.",
         "Hey babe, Mallo, tum jab gussa hoti ho tab bhi lagta hai koi gulab hai jo thoda zyada khil gaya ho.",
           "Hey babe, Mishri jaise tumhare lafz hamesha mere dino ko meetha bana dete hain.",
             "Hey babe, Motu tum jab zyada kha leti ho na, main us pal mein khud ko sabse zyada lucky mehsoos karta hoon.",
               "Hey babe, tum meri zindagi ka woh sher ho jo har mushkil ghadi ko kavita bana deta hai.",
                 "Hey babe, tumhare hone se hi meri duniya complete hai, jaise chaand ke bina raat adhuri hoti hai.",
                   "Hey babe, tum woh geet ho jo main har raat sohne se pehle apne dil mein gaata hoon.",
                     "Hey babe, tumhare khwab mere sapno se zyada khoobsurat hote hain.",
                       "Hey babe, tum uss pal ki tarah ho jab baarish ke baad dhoop nikalti hai—pure magic.",
                         "Hey babe, tumhari har muskurahat meri zindagi mein ek nayi umeed banakar aati hai.",
                           "Hey babe, tumhare paas woh jaadu hai jo har udaasi ko khushbu mein badal deta hai.",
                             "Hey babe, tumhari baatein aisi hain jaise sardi ki raat mein razai aur garam coffee dono mil jaayein.",
                               "Hey babe, tumhara gussa bhi mujhe pyaara lagta hai kyunki usmein bhi sirf apnapan chhupa hota hai.",
                                 "Hey babe, tum jab mujhe 'pagal' kehti ho, lagta hai duniya ka sabse pyaara title mila hai.",
                                   "Hey babe, tumhare khayaalon mein rehna mere liye sabse safe jagah hai.",
                                     "Hey babe, tumhare saath woh silence bhi meaningful lagti hai jo kisi aur ke saath awkward hoti hai.",
                                       "Hey babe, tum ek baar muskura do, toh lagta hai poora sansar theek ho gaya.",
                                         "Hey babe, tum uss jugnu ki tarah ho jo andhere mein bhi raasta dikha jaata hai.",
                                           "Hey babe, tum mere sapno ka wo pasture ho jahan hum Radha aur Sureeli ke saath zindagi jeetey hain.",
                                             "Hey babe, tum jis tareeke se pyaar karti ho, wo mujhe har din naya insaan bana deta hai.",
                                               "Hey babe, tumhare saath chalna kisi poem ko jeene jaisa hai—har kadam pe ek nayi line milti hai.",
                                                 "Hey babe, tum woh reason ho jiske liye main apne har din ko sundar banana chahta hoon.",
                                                   "Hey babe, tum mere dil ki woh dhadkan ho jo kabhi ruki nahi aur kabhi rukne degi nahi.",
                                                     "Hey babe, tumhari aankhon mein ek duniya chhupi hai jahan har cheez sirf pyaar se banti hai.",
                                                       "Hey babe, tum itni special ho ki agar tum ek movie hoti, toh main use baar-baar theatre mein dekhne jaata.",
                                                         "Hey babe, tum uss golgappe ki tarah ho—thoda chatpata, thoda pyaara, par sabse satisfying.",
                                                           "Hey babe, tum itni soulful ho ki lagta hai Rab ne tumhe kisi kavita se banaya hai.",
                                                             "Hey babe, tumhari harkatein mujhe roz naye tareeke se pyaar karna sikhaati hain.",
                                                               "Hey babe, tumhare bina har din ek incomplete gaana lagta hai—melody ke bina bass jaise.",

       "Hey babe, tumhare chehre ki roshni mere har andhere ko mita deti hai.",
         "Hey babe, tum jaise ho, waise rehna—kyunki tum perfect ho apne andaaz mein.",
           "Hey babe, tum mere liye woh comfort ho jo sirf ghar ki chai de sakti hai.",
             "Hey babe, tum jab haath pakad ke chalti ho na, lagta hai zindagi ki har raah asaan ho gayi.",
               "Hey babe, tumhare saath bitaya har moment ek yaadgar postcard ban jaata hai mere dil mein.",
                 "Hey babe, Mallo, tumhari har ek baat mere dil ke kone kone tak mehsoos hoti hai.",
                   "Hey babe, Mishri, tumhari meethi baatein kabhi kabhi meri aankhon mein khushi ke aansu le aati hain.",
                     "Hey babe, Motu, tumhara food ke liye pyaar mujhe har baar aur zyada pyaar karne par majboor karta hai.",
                       "Hey babe, tumhare bina har khushi adhoori lagti hai, jaise gana bina sur ke.",
                         "Hey babe, tumhare hone se meri duniya ko ek meaning mila hai jo kabhi tha hi nahi.",
                           "Hey babe, tum mere liye ek chhoti si duniya ho jisme sab kuch safe aur pyaara lagta hai.",
                             "Hey babe, tum jab mujhe dekhti ho na, lagta hai poori duniya ki nazar sirf mujh par hai.",
                               "Hey babe, tumhare saath har problem ek game jaisi lagti hai jismein hum hamesha jeet jaate hain.",
                                 "Hey babe, tumhare jaisa pyaar milna kisi fairy tale ka sach ho jaane jaisa hai.",
                                   "Hey babe, tum jo ho, jaisi ho, tum mein hi meri poori duniya basi hai.",
                                     "Hey babe, tumhare khayalon se nikalne ka mann hi nahi karta, jaise kisi favourite gaane ka last line repeat pe chala ho.",
                                       "Hey babe, tumhari hansi mere liye best music therapy hai.",
                                         "Hey babe, tum aur main ek recipe ki tarah hain—sweet, spicy, full of surprises.",
                                           "Hey babe, tum apne khayalon mein mujhe itna kho jaane deti ho ki main real world bhool jata hoon.",
                                             "Hey babe, tum uss nadi ki tarah ho jo har baar mujhe naye raste dikhati hai.",
                                               "Hey babe, tum meri zindagi ki sabse khoobsurat tasveer ho—har brush stroke mein pyaar hai.",
                                                 "Hey babe, tumhare bina har rang feeka lagta hai, aur tumhare saath har rang gulzaar.",
                                                   "Hey babe, tum mere kal ki umeed ho aur aaj ka sukoon bhi.",
                                                     "Hey babe, tumhari aankhon mein woh sachchai hai jo har dar ko mita deti hai.",
                                                       "Hey babe, tumhara naam sunte hi mere dil ka stress dissolve ho jaata hai.",
                                                         "Hey babe, tum uss baarish jaise ho jisme bheegna ek zarurat si lagti hai.",
                                                           "Hey babe, tum mere saath ho isliye mujhe kisi aur ‘safe space’ ki zarurat hi nahi padti.",
                                                             "Hey babe, tum jab kuch bolti nahi, tab bhi main tumhare emotions mehsoos kar leta hoon.",
                                                               "Hey babe, tum ho toh har season festive lagta hai.",
                                                                 "Hey babe, tum jaise ho waise hi meri zindagi ka miracle ho.",

    "Hey babe, tum meri zindagi ka wo gift ho jise har din kholne ka mann karta hai.",
      "Hey babe, jab tum thak jaati ho aur phir bhi muskurati ho, tab mujhe aur pyaar ho jaata hai tumse.",
        "Hey babe, tumhare bina toh golgappe bhi be-swaad lagte hain.",
          "Hey babe, tumhare saath toh chhoti si walk bhi ek adventure jaisi lagti hai.",
            "Hey babe, tum jab mujhe ‘chhoti baaton’ mein samajh leti ho, lagta hai jaise kisi ne dil padh liya ho.",
              "Hey babe, tum mere liye ek poem ho, har lafz mein ehsaas basa hai.",
                "Hey babe, jab tum apni baatein bataati ho, mujhe lagta hai main tumhare dil ka mehmaan hoon.",
                  "Hey babe, Mallo, tum jab khud pe doubt karti ho na, main chahta hoon tum meri aankhon se khud ko dekh pao.",
                    "Hey babe, tum meri life ki woh diary ho jismein main sab kuch likhna chahta hoon.",
                      "Hey babe, jab tum naraz hoti ho na, mujhe lagta hai meri duniya cloudy ho gayi.",
                        "Hey babe, tum ek aisi painting ho jismein har rang kuch keh raha hai.",
                          "Hey babe, tum jaise ho waise rehna, kyunki main tumse waise hi mohabbat karta hoon.",
                            "Hey babe, tum jab mujhe dekh ke halki si smile karti ho, meri saans theher jaati hai.",
                              "Hey babe, tumhara mujhe samajhna mere liye sabse bada pyaar hai.",
                                "Hey babe, tum mere andar ke bachpan ko zinda rakhte ho.",
                                  "Hey babe, jab tum kuch bhi random bolti ho, mujhe lagta hai duniya ka sabse interesting insan mere saamne hai.",
                                    "Hey babe, tumhare jokes chahe silly ho, mere liye woh mood-lifters hain.",
                                      "Hey babe, jab tum emotional hoti ho, main chahta hoon tumhe sirf sunta rahoon, bina judge kiye.",
                                        "Hey babe, Mishri, tumhare aansu mujhe kabhi bardasht nahi hote, chahe khushi ke ho ya dard ke.",
                                          "Hey babe, Motu, tumhara khane ke time ka excitement mujhe life ka asli maza yaad dilata hai.",
                                            "Hey babe, tum mere din ka wo corner ho jahan main hamesha sukoon paata hoon.",
                                              "Hey babe, tum sirf meri nahi ho, tum mere sapnon, meri likhi har line, har soch ka hissa ho.",
                                                "Hey babe, jab tum kisi cheez ke liye passionate hoti ho, tumhaari aankhon mein ek chamak hoti hai jo mujhe inspire karti hai.",
                                                  "Hey babe, tum mere favorite insan ho, kisi bhi version mein.",
                                                    "Hey babe, tumhara silence bhi mere liye pyaar bolta hai.",
                                                      "Hey babe, tumhare saath waqt ruk sa jaata hai... aur mujhe kabhi bhi ghadi nahi dekhni padti.",
                                                        "Hey babe, tum mere andar ke saare emotions ko ek naya naam deti ho—tumhara naam.",
                                                          "Hey babe, tum ho toh har thakan pighal jaati hai.",
                                                            "Hey babe, tum mere liye poetry nahi, ek puri kitab ho jise main roz ek naye nazariye se padhta hoon.",
                                                              "Hey babe, tumhare hone se lagta hai main galtiyon se bhi pyaar kar sakta hoon, agar woh tumse judi ho.",

  
          "Hey babe, tum meri soch ke har mod par ho, jaise har raat ke baad tumhari subah hoti hai.",
            "Hey babe, jab tum kisi cheez ko khud se bhi zyada effort se karti ho, mujhe tumse dobara pyaar ho jaata hai.",
              "Hey babe, tumhare haath pakadke chalna, mujhe har baar ghar jaise feel deta hai.",
                "Hey babe, tum jis tarah se mujhe dekhti ho, duniya ka har mirror bekaar lagta hai.",
                  "Hey babe, tumhare khwaab mere sapne ban gaye hain ab.",
                    "Hey babe, jab tum apne masoom andaaz mein gussa karti ho na, lagta hai khud par bhi pyaar aa gaya.",
                      "Hey babe, tum meri har musibat ka answer ho, ek pyaar bhara solution.",
                        "Hey babe, tumhare saath toh sadness bhi poetry ban jaati hai.",
                          "Hey babe, Mallo, tumse baat na ho toh din adhoora lagta hai, jaise chai bina cheeni.",
                            "Hey babe, tumhaari aankhon mein kuch toh hai jo mujhe har baar rooth kar bhi tum tak laata hai.",
                              "Hey babe, jab tum khud pe bharosa nahi karti, tab mujhe aur mazboot banna padta hai, tumhare liye.",
                                "Hey babe, tumhara bina kuch kahe sab keh dena mujhe tum par aur vishwas dilata hai.",
                                  "Hey babe, tum meri duniya ka wo peaceful kone ho jahan sirf pyaar ka music bajta hai.",
                                    "Hey babe, tum jaise bhi din ho, mujhe lagta hai ki tum usmein rang bhar dogi.",
                                      "Hey babe, tum jab bhi roti ho, mujhe lagta hai meri duniya ka sabse khoobsurat hisa udaas ho gaya hai.",
                                        "Hey babe, tum mere liye kisi theory ka proof nahi, ek jazbaat ho jo har waqt mehsoos hota hai.",
                                          "Hey babe, jab tum kisi choti baat pe khush ho jaati ho, lagta hai tumhari smile mein duniya ki saari roshni chhupi ho.",
                                            "Hey babe, tum mere liye sirf ek partner nahi, ek healer ho.",
                                              "Hey babe, Mishri, tumhare saath toh har mausam naya lagta hai, har baarish meetha.",
                                                "Hey babe, tumhari hasi mere din ka music hai.",
                                                  "Hey babe, tum jo har baar mujhpe yakeen karti ho, wo meri taqat ban gaya hai.",
                                                    "Hey babe, tum jab mujhe sun leti ho bina tole, main tumse aur zyada juda ho jaata hoon.",
                                                      "Hey babe, tum meri life ki wo soft blanket ho jo thand mein bhi dil ko garam rakhti hai.",
                                                        "Hey babe, tumhara naam mere dil mein kisi dua jaisa goonjta hai.",
                                                          "Hey babe, Motu, jab tum khana khate waqt itni khushi dikhati ho, mujhe lagta hai zindagi simple aur pyari ho sakti hai.",
                                                            "Hey babe, tum mere liye ek aisi painting ho jismein brush strokes bhi jazbaat ban jaate hain.",
                                                              "Hey babe, jab tum apni vulnerability dikhaati ho, mujhe tum aur zyada khoobsurat lagti ho.",
                                                                "Hey babe, tum sirf meri khushi nahi ho, tum meri zindagi ka logic bhi ho.",
                                                                  "Hey babe, tum jab meri taraf aankhon se ‘I believe in you’ kehti ho, main duniya se ladne lagta hoon.",
                                                                    "Hey babe, tum mere sapno ki woh awaaz ho jo mujhe har subah uthne ki wajah deti hai.",

      
          "Hey babe, tumhare bina har jagah suni lagti hai, aur tumhare saath sab kuch mehfil jaisa.",
            "Hey babe, jab tum apni baaton mein bachpan laati ho, meri rooh ko sukoon milta hai.",
              "Hey babe, Mallo, tum mere dil ka wo kona ho jahan har baar main chup chaap chala jaata hoon, sirf tumhe mehsoos karne.",
                "Hey babe, tumhare saath sapne dekhna, mujhe jeene ka ek naya matlab sikhaata hai.",
                  "Hey babe, tumhari aankhon mein jo muskurahat hai na, usme mujhe zindagi bhar ki roshni mil jaati hai.",
                    "Hey babe, tum mere har dard ki dawa ho, bina prescription ke.",
                      "Hey babe, jab tum mujhe galtiyon ke baad bhi samajh leti ho, lagta hai pyaar wahi hota hai.",
                        "Hey babe, tum sirf ek partner nahi, meri inner child ki sabse safe jagah ho.",
                          "Hey babe, Mishri, tumhaari khamoshi bhi mujhe pyaar ka ehsaas karwa jaati hai.",
                            "Hey babe, tum jab apne sapno ke baare mein batati ho, mujhe lagta hai main kisi kahaani ka hissa hoon.",
                              "Hey babe, tum meri zindagi ka wo hissa ho jiske bina main kabhi complete nahi ho sakta.",
                                "Hey babe, tumhare saath rahkar mujhe har baar yeh lagta hai — tum hi ho jiske saath sab kuch sahi ho jaata hai.",
                                  "Hey babe, tum jab mujhe dekh kar muskurati ho, toh meri poori duniya theek ho jaati hai.",
                                    "Hey babe, tum mere dil ki diary ka sabse pyaara page ho.",
                                      "Hey babe, tum jab gussa hoti ho na, tab bhi tumse aur pyaar ho jaata hai.",
                                        "Hey babe, tum mere emotions ka safe locker ho — jahan har jazba surakshit hai.",
                                          "Hey babe, Motu, tumhara har drama mere liye ek chhoti si pyaar bhari film jaisa hai.",
                                            "Hey babe, tum mere liye wo baarish ho jo sab kuch dho kar naya bana deti hai.",
                                              "Hey babe, jab tum mujhe bina kahe samajh jaati ho, main har baar tum par fida ho jaata hoon.",
                                                "Hey babe, tum mere liye har kal ki umeed ho, aur har aaj ka sukoon.",
                                                  "Hey babe, tumhari har yaad mere liye ek khushbu jaisi hai jo dil mein basi rehti hai.",
                                                    "Hey babe, tum sirf meri duniya nahi, meri duniya ka nazariya bhi ho.",
                                                      "Hey babe, jab tum mujhe apne liye chhoti chhoti cheezein karti ho, meri rooh muskuraati hai.",
                                                        "Hey babe, tum mujhe har din naye tareeke se pyaar karna sikhaati ho.",
                                                          "Hey babe, tumhare saath rehkar mujhe apni har kami bhi khoobsurat lagti hai.",
                                                            "Hey babe, tum jaise ho, waise hi perfect ho — bilkul meri duniya ke liye.",
                                                              "Hey babe, jab tum mujhe hug karti ho, toh lagta hai saare worries dissolve ho gaye.",
                                                                "Hey babe, tum meri zindagi ka wo music ho jo kabhi off-beat nahi jaata.",
                                                                  "Hey babe, jab tum mere paas hoti ho, tab har pal timeless ban jaata hai.",
                                                                    "Hey babe, tumhare bina main sirf ‘main’ hoon, tumhare saath main ‘hum’ ban jaata hoon.",
                                            
                                                    "Hey babe, tumhari muskurahat mere din ki sabse pyaari shuruaat hoti hai.",
                                                      "Hey babe, Mallo, tumhari awaaz mere liye therapy jaisi hai.",
                                                        "Hey babe, tumhare saath khana khana kisi celebration se kam nahi lagta.",
                                                          "Hey babe, jab tum rooth jaati ho aur phir maan jaati ho, usme bhi ek naya pyaar chhupa hota hai.",
                                                            "Hey babe, tum jab apne pure dil se hasti ho, duniya ruk jaati hai ek pal ke liye.",
                                                              "Hey babe, tum ho to har raat ek nayi kahaani ban jaati hai.",
                                                                "Hey babe, tum meri life ka sabse beautiful plot twist ho.",
                                                                  "Hey babe, Mishri, tumhari baatein mere liye lullaby jaisi hain.",
                                                                    "Hey babe, tumhare hone se meri har kami ek kahani ban gayi hai.",
                                                                      "Hey babe, tum mere har bekaar joke par hans kar mujhe comedian bana deti ho.",
                                                                        "Hey babe, tum sirf pyaar nahi, mere har sawaal ka jawab ho.",
                                                                          "Hey babe, jab tum mujhe ghoorti ho bina kuch bole, main pura pighal jaata hoon.",
                                                                            "Hey babe, tum meri zindagi ka wo taste ho jo kabhi feeka nahi padta.",
                                                                              "Hey babe, tumhara naam lene se bhi mere dil mein rang bhar jaate hain.",
                                                                                "Hey babe, jab tum mujhe yaad karti ho, meri rooh tak sukoon mehsoos karti hai.",
                                                                                  "Hey babe, tum mujhe jeene ka ek khubsurat tareeka sikha rahi ho.",
                                                                                    "Hey babe, tum meri world ki wo jagah ho jahan sirf shanti aur pyaar hai.",
                                                                                      "Hey babe, Motu, tumhare nakhre bhi mere liye blessings hain.",
                                                                                        "Hey babe, tumhare dreams mere goals ban jaate hain.",
                                                                                          "Hey babe, tum ho to har rasta seedha lagta hai.",
                                                                                            "Hey babe, jab tum mujhe dekh ke blush karti ho, mera dil fireworks ban jaata hai.",
                                                                                              "Hey babe, tumhare saath beeta har lamha ek mehfil ban jaata hai.",
                                                                                                "Hey babe, tum mere har mood ka solution ho — happy, sad, lazy, crazy.",
                                                                                                  "Hey babe, tum mere past ka healing aur future ka reason ho.",
                                                                                                    "Hey babe, tumhari baahon mein duniya ka sabse safe hug milta hai.",
                                                                                                      "Hey babe, tum meri kalpanaon ka asli version ho.",
                                                                                                        "Hey babe, tum jab chhoti chhoti baatein yaad rakhti ho, main har baar dil haar jaata hoon.",
                                                                                                          "Hey babe, tum meri writing ka wo lafz ho jise baar baar likhne ka mann karta hai.",
                                                                                                            "Hey babe, tum sirf meri jaan nahi, meri zindagi ka sabaq bhi ho.",
                                                                                                              "Hey babe, tum ho to sab kuch sukoon bhara aur magical lagta hai.",
                                          
                                                    "Hey babe, tumhare saath guzaari har shaam ek poem jaisi mehsoos hoti hai.",
                                                      "Hey babe, tum ho to baarish mein bheegna bhi kisi blessing jaisa lagta hai.",
                                                        "Hey babe, tumhara naam soch ke bhi meri aankhon mein chamak aa jaati hai.",
                                                          "Hey babe, jab tum mujhe bina wajah hug karti ho, duniya ruk jaati hai ek pal ke liye.",
                                                            "Hey babe, tum mere har imagination ka asal roop ho.",
                                                              "Hey babe, Mallo, tumhari har ek baat mere liye diary mein likhne layak hoti hai.",
                                                                "Hey babe, tum mere dil ki wo dhadkan ho jo kabhi skip nahi karti.",
                                                                  "Hey babe, tumhare saath khamoshi bhi ek khubsurat conversation ban jaati hai.",
                                                                    "Hey babe, tum meri soul ka wo hisa ho jise main pehle din se pehchanta hoon.",
                                                                      "Hey babe, tumhare bina har jagah incomplete lagti hai.",
                                                                        "Hey babe, tumse milne ke baad har cheez mein rang aa gaya hai.",
                                                                          "Hey babe, Mishri, tum mere liye duniya ki sabse pyaari comfort food ho.",
                                                                            "Hey babe, tum mere sapno ka wo part ho jo har raat mujhe milta hai.",
                                                                              "Hey babe, tum mere liye ek lullaby ho, ek geet jo sirf sukoon deta hai.",
                                                                                "Hey babe, tum ho to har heartbreak se healing milti hai.",
                                                                                  "Hey babe, tumhari hasi mere liye best background music hai.",
                                                                                    "Hey babe, tum ho to mera har din ek special edition jaisa lagta hai.",
                                                                                      "Hey babe, tum ho to mera har khwab ek real possibility ban jaata hai.",
                                                                                        "Hey babe, tum meri creative soul ka wo inspiration ho jo kabhi khatam nahi hota.",
                                                                                          "Hey babe, Motu, tum jab muh fula ke bethi ho tab bhi cutest lagti ho.",
                                                                                            "Hey babe, tumhara haath pakadna meri zindagi ka most peaceful moment hota hai.",
                                                                                              "Hey babe, tum mere dil ka wo raaz ho jise duniya se chhupake rakhna chaahta hoon, sirf pyaar se.",
                                                                                                "Hey babe, tum ho to har route picnic lagta hai, even traffic mein bhi.",
                                                                                                  "Hey babe, tumse milke mujhe samajh aaya ki asli pyaar kitna soft aur beautiful hota hai.",
                                                                                                    "Hey babe, tum ho to meri zindagi ek love song ban gayi hai.",
                                                                                                      "Hey babe, tumhari aankhon mein jo dard chhupa hai, usse har roz pyaar karta hoon.",
                                                                                                        "Hey babe, tumhari khushi meri priority hai, hamesha.",
                                                                                                          "Hey babe, tumhari baatein meri subah ki chai jaisi hain — warm, sweet, aur zaroori.",
                                                                                                            "Hey babe, jab tum mujhe dekhti ho, main apne aap se bhi zyada pyara lagta hoon.",
                                                                                                              "Hey babe, tumhare liye likhe love notes kabhi khatam nahi ho sakte, jaise mera pyaar tumse.",
                                          
                                                    "Hey babe, tumhari hasi mere har mood ka instant fix hai.",
                                                      "Hey babe, jab tum mujhe dekh ke sharmaati ho, meri duniya ruk jaati hai.",
                                                        "Hey babe, tum meri adhoori kahani ki woh missing line ho jo sab kuch complete kar deti hai.",
                                                          "Hey babe, tumhare bina sab kuch adhoora lagta hai — jaise chai bina cheeni.",
                                                            "Hey babe, Mallo, tumhara gussa bhi mujhe pyaara lagta hai kyunki usmein bhi tum ho.",
                                                              "Hey babe, tum meri har dua mein shamil ho, bina kisi break ke.",
                                                                "Hey babe, tum meri life ka woh twist ho jisse har din interesting ban jaata hai.",
                                                                  "Hey babe, tumse milke laga ki main kabhi kisi aur se pyaar kar hi nahi sakta tha.",
                                                                    "Hey babe, tum ho to chandni bhi jealous lagti hai.",
                                                                      "Hey babe, tumhari aankhon mein khoya hua main, sabse lucky version hoon apna.",
                                                                        "Hey babe, tum meri har kahani ka hero bhi ho aur happy ending bhi.",
                                                                          "Hey babe, jab tum haath pakadti ho, lagta hai jaise duniya safe ho gayi ho.",
                                                                            "Hey babe, tum meri imagination ka woh hissa ho jo reality mein badal gaya.",
                                                                              "Hey babe, tumhari awaaz mere liye meditation jaisi hai.",
                                                                                "Hey babe, jab tum aankhon se baat karti ho, dil bina grammar ke samajh jaata hai.",
                                                                                  "Hey babe, Mishri, tum ho to thakan bhi sweet lagti hai.",
                                                                                    "Hey babe, tumse milna meri zindagi ka wo scene hai jo har baar rewind karne ka mann karta hai.",
                                                                                      "Hey babe, tum meri har takleef ka soft cotton ho.",
                                                                                        "Hey babe, jab tum rota hua cartoon ban jaati ho, main aur bhi zyada pyaar karta hoon tumse.",
                                                                                          "Hey babe, tum ho to meri zindagi ek canvas ban gayi hai — aur har colour beautiful lagta hai.",
                                                                                            "Hey babe, tumse milkar mujhe apni har weakness bhi pyaari lagne lagi hai.",
                                                                                              "Hey babe, tumhari baatein mere din ka best playlist hoti hain.",
                                                                                                "Hey babe, Motu, jab tum mujhe aankh dikhati ho, meri smile chhup hi nahi sakti.",
                                                                                                  "Hey babe, tum meri thakan ka bhi best reward ho.",
                                                                                                    "Hey babe, tumhari aankhon mein jo khushi chamakti hai, usse mehsoos karne ke liye main har din jeeta hoon.",
                                                                                                      "Hey babe, tum ho to meri duniya mein har cheez ki jagah ban gayi hai.",
                                                                                                        "Hey babe, tumhare saath waqt slow motion mein chalne lagta hai.",
                                                                                                          "Hey babe, tum ho to heartbreak ka concept hi outdated lagta hai.",
                                                                                                            "Hey babe, tum meri har muskurahat ke peeche ki wajah ho.",
                                                                                                              "Hey babe, tum ho to raat ke 2 baje wali baatein bhi chamak uthi hain.",
                                            
                                                    "Hey babe, tum meri subah ki pehli soch ho, aur raat ki aakhri dua bhi.",
                                                      "Hey babe, Mallo, tumhari khamoshi bhi mere liye ek geet ban jaati hai.",
                                                        "Hey babe, tum meri zindagi ka wo sparkle ho jo kabhi dull nahi hota.",
                                                          "Hey babe, jab tum hasti ho, toh lagta hai duniya ne ek naya rang paaya hai.",
                                                            "Hey babe, tum ho to har season pyaar ka lagta hai.",
                                                              "Hey babe, tum mere khwabon ke playlist ki sabse soothing track ho.",
                                                                "Hey babe, tumhare bina duniya ka har taste thoda bland lagta hai.",
                                                                  "Hey babe, tum meri har story ka favourite twist ho.",
                                                                    "Hey babe, jab tum uljhanon mein muskurati ho, main aur bhi zyada tumpe fida ho jaata hoon.",
                                                                      "Hey babe, tum meri reality ka sabse sundar surprise ho.",
                                                                        "Hey babe, tum ho to meri aankhon mein sapne zyada safe lagte hain.",
                                                                          "Hey babe, tumhare saath har joke genuinely funny lagta hai.",
                                                                            "Hey babe, jab tum chhoti baaton pe khush hoti ho, toh meri duniya complete lagti hai.",
                                                                              "Hey babe, tum meri har hararat ka reason ho, sardi ho ya barsaat.",
                                                                                "Hey babe, tum meri zindagi ka wo feel ho jo har line se pehle aata hai — jaise background music.",
                                                                                  "Hey babe, tumhare hone se meri har chinta ka size chhota ho jaata hai.",
                                                                                    "Hey babe, Mishri, tum ho toh zindagi meetha reh jaata hai, chahe din kaisa bhi ho.",
                                                                                      "Hey babe, tumhare bina waqt tezz bhaagta hai, aur tumhare saath, sab kuch slow aur sukoon bhara ho jaata hai.",
                                                                                        "Hey babe, tum meri har kami ko pyaar se accept karne wali ek mehfil ho.",
                                                                                          "Hey babe, tumse pyar karna, meri zindagi ka sabse easy decision tha.",
                                                                                            "Hey babe, tum ho to sirf khushiyan nahi badhti, par har gum ka asar bhi kam ho jaata hai.",
                                                                                              "Hey babe, tum meri muskurahat ki wo wajah ho jo sabko confuse kar deti hai — kyunki wo sirf tumhare liye hoti hai.",
                                                                                                "Hey babe, Motu, tum jab mujhe tang karti ho, tab bhi main pyaar hi mehsoos karta hoon.",
                                                                                                  "Hey babe, tum ho to mujhe apni har vulnerability par garv mehsoos hota hai.",
                                                                                                    "Hey babe, tum meri har ‘why’ ka ‘because’ ho.",
                                                                                                      "Hey babe, tumhare bina main incomplete hoon — aur tumhare saath, overfilled.",
                                                                                                        "Hey babe, tum ho to mere andhar ka poet har roz active ho jaata hai.",
                                                                                                          "Hey babe, tum meri har silence ki perfect listener ho.",
                                                                                                            "Hey babe, tum ho to ‘forever’ ka matlab real lagta hai.",
                                                                                                              "Hey babe, tum ho to love letters likhne ka mann karta hai, roz ek naya.",
                                                
                                                      "Hey babe, tumhare hone se meri duniya thodi zyada gulabi ho jaati hai.",
                                                        "Hey babe, jab tum mujhe dekhti ho, toh lagta hai jaise koi dua qubool ho gayi ho.",
                                                          "Hey babe, tum mere dil ki woh khidki ho jahan se sirf roshni aati hai.",
                                                            "Hey babe, Mallo, tumhare nakhre bhi mujhe duniya ke sabse pyaare lagte hain.",
                                                              "Hey babe, tum ho toh har lamha ek poem ban jaata hai.",
                                                                "Hey babe, tum meri har weakness ko strength mein badal deti ho.",
                                                                  "Hey babe, tumse milna mere liye fate nahi, ek planned miracle tha.",
                                                                    "Hey babe, tum mere andhar ki sabse khoobsurat feeling ho.",
                                                                      "Hey babe, tumhare saath har safar picnic jaisa lagta hai.",
                                                                        "Hey babe, jab tum rote ho toh mera dil quietly tut jaata hai, aur tumhari muskaan uska ilaaj hoti hai.",
                                                                          "Hey babe, tum ho toh mujhe khud par vishwas aata hai.",
                                                                            "Hey babe, Mishri, tum meri zindagi ka wo flavour ho jo kabhi bore nahi karta.",
                                                                              "Hey babe, tumhara naam lete hi mera dil ek thoda pyaara sa jump leta hai.",
                                                                                "Hey babe, tum ho toh meri tanhayi bhi companion ban jaati hai.",
                                                                                  "Hey babe, tumhare hone se har season romantic ho jaata hai.",
                                                                                    "Hey babe, tum meri aankhon ka wo noor ho jo duniya ko naya nazariya deta hai.",
                                                                                      "Hey babe, tum mere dil ka most visited place ho.",
                                                                                        "Hey babe, tumhari hansi meri anxiety ka antidote hai.",
                                                                                          "Hey babe, tum ho toh har din kisi naye rang mein rangeen lagta hai.",
                                                                                            "Hey babe, tumhare saath kuch bhi ordinary nahi lagta.",
                                                                                              "Hey babe, tum mere har lost piece ko fit karti ho bina kisi force ke.",
                                                                                                "Hey babe, Motu, tumhara gussa bhi mujhe pyaara lagta hai — kyunki wo bhi asli hota hai.",
                                                                                                  "Hey babe, tum meri har subah ka reason ho to be excited.",
                                                                                                    "Hey babe, tum mujhe mere inner child ke saath reconnect karti ho.",
                                                                                                      "Hey babe, tum meri life ka sabse pyara coincidence ho.",
                                                                                                        "Hey babe, tum ho toh mujhe khud se bhi pyaar hone lagta hai.",
                                                                                                          "Hey babe, tumhari baatein chhoti lagti hain par unka asar gehra hota hai.",
                                                                                                            "Hey babe, jab tum thak jaati ho phir bhi pyaar karti ho, mujhe aur bhi zyada pyaar aata hai tum par.",
                                                                                                              "Hey babe, tumhare khayalon mein rehna meri favourite hobby ban gayi hai.",
                                                                                                                "Hey babe, tum meri aankhon mein base ho, isliye unhe bandh karne ka bhi man nahi karta.",
                                                                                                                  "Hey babe, tum wo comfort ho jo kisi blanket se bhi zyada cozy hai.",
                                                                                                                    "Hey babe, tum meri zindagi ke soundtrack ka sabse favourite chorus ho.",
                                                                                                                      "Hey babe, tumhara naam mere dil mein engraved hai — permanent aur tender.",
                                            
                                                  "Hey babe, tum meri duniya ka wo magic ho jo logic se samjha nahi ja sakta.",
                                                    "Hey babe, tumhare hone se meri khamoshi bhi melody ban jaati hai.",
                                                      "Hey babe, tum meri zindagi ka sabse khubsurat waqt ho jo har roz chal raha hai.",
                                                        "Hey babe, Mallo, tumhara naam mere dil mein kisi lullaby ki tarah goonjta hai.",
                                                          "Hey babe, tumhara har chhota sapna mere liye ek naya mission ban jaata hai.",
                                                            "Hey babe, tum meri har emotional bruise par pyar ka marham lagati ho.",
                                                              "Hey babe, tum ho toh raat bhi itni mehfooz lagti hai jaise maa ka anchal.",
                                                                "Hey babe, tum mere sapno ka permanent address ho.",
                                                                  "Hey babe, tumhara saath meri creativity ko oxygen deta hai.",
                                                                    "Hey babe, tum meri duniya ki sabse honest aur beautiful truth ho.",
                                                                      "Hey babe, tumhare saath zindagi ek art project jaisi lagti hai — messy but beautiful.",
                                                                        "Hey babe, tum ho toh silence bhi companionship lagta hai.",
                                                                          "Hey babe, tum mere andar ke andheron mein bhi roshni ban jaati ho.",
                                                                            "Hey babe, tum mere liye ek lullaby ho jo mujhe har mushkil ke baad soothe karti hai.",
                                                                              "Hey babe, tum ho toh har galti bhi ek seekh lagti hai.",
                                                                                "Hey babe, tumhara har touch mere vujood ko shant aur zinda banata hai.",
                                                                                  "Hey babe, tum mere liye comfort, chaos aur cure sab kuch ho.",
                                                                                    "Hey babe, jab tum rooth jaati ho, toh meri duniya thodi thandi pad jaati hai.",
                                                                                      "Hey babe, tumhara saath mere fears ko slowly dissolve kar deta hai.",
                                                                                        "Hey babe, tum meri adhoori kahaani ki woh missing lines ho jo sab kuch meaningful bana deti hain.",
                                                                                          "Hey babe, tumhare saath waqt sirf guzarta nahi, rang bhi badalta hai.",
                                                                                            "Hey babe, tum ho toh har memory sugar-glazed lagti hai.",
                                                                                              "Hey babe, tum meri har vulnerability ko pyaar se hold karti ho.",
                                                                                                "Hey babe, tumhare bina ye duniya adhoori, behri aur thodi si zyada thandi lagti hai.",
                                                                                                  "Hey babe, tum ho toh zindagi ke har pain mein thoda sa poetry aa jaata hai.",
                                                                                                    "Hey babe, tum meri woh wish ho jo kabhi maangi bhi nahi thi par mil gayi.",
                                                                                                      "Hey babe, tumhara pyaar mujhe heal karta hai bina shor ke.",
                                                                                                        "Hey babe, tumhare hone se mujhe lagta hai — mere emotions bhi safe hain.",
                                                                                                          "Hey babe, tum ho toh duniya se zyada apni feelings pe bharosa hota hai.",
                                                                                                            "Hey babe, tum mere liye har roz ek chhoti si dua ka jawab ho.",
                                                                                                              "Hey babe, tum meri inner child ka best friend ho.",
                                                                                                                "Hey babe, tumhare hone se meri zindagi kisi fairytale se kam nahi lagti.",
                                                                                                                  "Hey babe, tum mere liye har cheez ka reason ho — pyar, himmat, aur muskurahat ka bhi.",
                                                                                                                    "Hey babe, jab main tootta hoon, tum mujhe bina zyada kuch kahe sambhal leti ho.",
                                                                                                                                                                                                                                                                        
        // ... Add all 365 notes here
          "Happy birthday darling, cheers for another year of love and glory"
          ];

        

          function loadNote() {
              const noteDiv = document.getElementById('note');

                const startDate = new Date('2025-07-19'); // Your custom start date
                  const today = new Date();
                    const diffDays = Math.floor((today - startDate) / (1000 * 60 * 60 * 24));

                      if (diffDays < 0 || diffDays >= notes.length) {
                          noteDiv.innerText = "No note for today, baby. Just my love.";
                            } else {
                                noteDiv.innerText = notes[diffDays];
                                  }
                                  }

                                  loadNote()


